### ISSUE TITLE
Dates calculations are incorrect

### ISSUE THREAD

**Issue by baruchsheffi** [imliam/temphpest-issues#4]
![Screenshot from 2024-09-23 10-33-23](https://github.com/user-attachments/assets/2c7c239f-bd18-48c9-befd-027b1bebc147)
As you can see in the screen shot, temphpest shows the same date on all lines (2024-09-23) which is the current date.
this is the code:
```
if (empty($date)) {
     $date = date('Y-m-d', strtotime('sunday last week'));
}
$startDate = date('Y-m-d', strtotime('sunday last week', strtotime($date)));
$endDate = date('Y-m-d', strtotime('saturday', strtotime($date)));
```
on tinker those are the results:
```
> $date = date('Y-m-d', strtotime('sunday last week'));
= "2024-09-22"

> $startDate = date('Y-m-d', strtotime('sunday last week', strtotime($date)));
= "2024-09-15"

> $endDate = date('Y-m-d', strtotime('saturday', strtotime($date)));
= "2024-09-28"
```

**Comment by imliam** [comment]
This is intentional - it doesn't actually run the PHP code for the date lens - it just gives you an example of how the output will look using the current datetime.

If you want it to give you the real dates that'll be output, check out the REPL functionality.
